{% set version = '1.66.0-1' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-bh
  version: {{ version|replace("-", "_") }}

source:
  fn: BH_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/BH_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/BH/BH_{{ version }}.tar.gz
  sha256: 17d9eb5512d74aa7dd02ec98953408422e728b01ce63493a6a473070b9596a92

build:
  noarch: generic
  number: 2001
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base

  run:
    - r-base

test:
  commands:
    - $R -e "library('BH')"  # [not win]
    - "\"%R%\" -e \"library('BH')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=BH
  license: BSL-1.0
  summary: 'Boost provides free peer-reviewed portable C++ source  libraries.  A large part of
    Boost is provided as C++ template code which is resolved entirely at compile-time
    without linking.  This  package aims to provide the most useful subset of Boost
    libraries  for template use among CRAN package. By placing these libraries in  this
    package, we offer a more efficient distribution system for CRAN  as replication
    of this code in the sources of other packages is  avoided. As of release 1.65.0-1,
    the following Boost libraries are included: ''algorithm'' ''align'' ''any'' ''atomic''
    ''bimap'' ''bind'' ''circular_buffer'' ''concept'' ''config'' ''container'' ''date''_''time''
    ''detail'' ''dynamic_bitset'' ''exception'' ''filesystem'' ''flyweight'' ''foreach''
    ''functional'' ''fusion'' ''geometry'' ''graph'' ''heap'' ''icl'' ''integer'' ''interprocess''
    ''intrusive'' ''io'' ''iostreams'' ''iterator'' ''math'' ''move'' ''mpl'' ''multiprcecision''
    ''numeric'' ''pending'' ''phoenix'' ''preprocessor'' ''propery_tree'' ''random''
    ''range'' ''scope_exit'' ''smart_ptr'' ''sort'' ''spirit'' ''tuple'' ''type_traits''
    ''typeof'' ''unordered'' ''utility'' ''uuid''.'
  license_family: OTHER

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
