travis:
  secure:
    BINSTAR_TOKEN: MEPrGOg8zXVzhsnRu9tEbtYjEiRS3IhqhqnhTzlc3Q4DDlPWQuiyNAuIucZ7H/Jsfho0QP1GcVhN2lxg4YU2QGHvtr+dqqEWZs65wj9cuRJmIhCnxs21M7vcqSz1DY5NXoY1RZUaEBuArUqbm4ub18igrPlNZH33WVcEzkwcyPWfMRMqdDX8TYKwnHjbwDNZynLNesuqrht3dEUyJeEuRvBc7WK0s/r3b7J3GXrdA2EQgAUzUBrlo0A290qqt5OxAGVMFR39JyFURnJE5GPW1A41GiuM4MGn4JcZDYC5D1mZVPbyFCmUO22CaGntfu2z0Oc7dG1neB+8VP1WbOoyA9ocuThYMJei0gb7QPbw6mHyYZoFSoIlLsZBY9djZXa8Fb5Q1ocjIGAU6xdXKaeigL+8LRCG6o2bpPIRSqF9ylRgh3p3Sfdi0PjNDgO1mwdhV/KfdqxSs5Hz086CPwb1X5rk0iN5JJ+2FWAgSlBbhfukhoLTdbL+IqnoRfqGsIEnbyBPV/4iwP5qSTkA3n6gakI3/snrHpPKGpq8BsapJR4McYpcyOUFfHa7sqEnnDZFQCNTebsHMlI3GA+vdlqTldBW13LpRY+GM7+LiBqhm1t7GDQyg+wbA8uombay+0P9f0NQylxlTEzLAhlkVQNNB0qmGrS/CZ9ZZpsLSRHK5yc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
